spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/lost_found?characterEncoding=utf-8&useSSL=false
    username: root
    password: 15576123138

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true